<div class="contents1">
                                        <h3>TERMS &amp; CONDITIONS</h3>
                                        <div class="play">

                                        </div>
                                        <div class="contents-content">
                                            <p align="justify">
                                                Robert George "Bob" Windle (born 7 November 1944) is an Australian retired freestyle swimmer of the 1960s, who won four Olympic medals, including an individual gold medal. Windle won the 1500 m freestyle and took bronze in the 4 × 100 m freestyle relay at the 1964 Summer Olympics in Tokyo, and silver and bronze in the 4 × 200 m and 4 × 100 m freestyle relays respectively at the 1968 Summer Olympics. Known for his versatility, he is the only male swimmer to represent Australia at the Olympics in all freestyle distances from 100 m to 1500 m. During his career, Windle set six world records and won six Commonwealth Games gold medals. He won 19 Australian Championships in all distances from 220 yd to 1650 yd.
                                            </p>
                                            <p align="justify">

                                                Growing up in eastern Sydney, Windle was trained by Frank Guthrie from the age of 12. Windle's first major swimming competition was the 1960 Australian Championships. Aged 15, his second-place finish in the 1650 yd freestyle earned him a place on the team for the 1960 Summer Olympics in Rome. However, the Australian coaches only took him along to gain experience and he did not compete. He won his first national title in 1961—the 1650 yd freestyle—and claimed the 220–440–1650 yd treble in 1962. Windle made his international debut at the 1962 British Empire and Commonwealth Games in Perth, winning gold in the 4 × 220 yd freestyle and silver and bronze in the 1650 and 440 yd freestyle respectively. In 1963, he won four individual national titles, adding the 880 yd event to the successful defence of his three titles. He won three individual titles in 1964 and proceeded to the Tokyo Olympics where he was eliminated in the heats of the 400 m freestyle after attempting to save energy for the final. In response, Windle took an aggressive approach in the 1500 m and set Olympic records in the heats and final to win gold. He added a bronze in the 4 × 100 m freestyle relay.
                                            </p>
                                            <p align="justify">
                                                After the Olympics, Windle enrolled at Indiana University, where he trained under Doc Counsilman. While in the United States, Windle converted to sprint swimming. He competed in the 1966 British Empire and Commonwealth Games in Kingston, Jamaica, winning the 440 yd freestyle, 4 × 110 yd and 4 × 220 yd freestyle relays, all in world-record times. He competed in his second Olympics in Mexico City in 1968, racing the 100 m and 200 m freestyle and the corresponding relays, having completed his transition to sprinting. He won a bronze and silver in the respective relays and retired after the games. In retirement, he worked for Allis-Chalmers in the United States, before being transferred to their Australian division.
                                            </p>
                                        </div>
                                    </div>